use_frameworks!

platform :ios, '11.0'

target 'SeedSlideControl_Example' do
  pod 'SeedSlideControl', :path => '../'

  target 'SeedSlideControl_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
